// Spanish (source language) -> English for the installer. Keys with {name} are patterns.
export const EN: Record<string, string> = {
  'Instalador de DevPanel': 'DevPanel Installer',
  'Cuenta': 'Account',
  'Código': 'Code',
  'Instalar': 'Install',
  'Rostro': 'Face',
  'Tu centro de desarrollo, forjado a mano.': 'Your development hub, handcrafted.',
  'Buscando última versión…': 'Looking for the latest version…',
  'Versión {v} · {s}': 'Version {v} · {s}',
  'Sin conexión con GitHub': 'No connection to GitHub',
  'No se pudo obtener la última versión.': 'Could not get the latest version.',
  'Instalar ahora': 'Install now',
  'Personalizar': 'Customize',
  'Tus proyectos': 'Your projects',
  'Repos, commits y builds de GitHub en un vistazo.': 'GitHub repos, commits and builds at a glance.',
  'Login con tu rostro': 'Sign in with your face',
  'Biometría local, cifrada, sin subir nada.': 'Local, encrypted biometrics. Nothing is uploaded.',
  'Siempre al día': 'Always up to date',
  'Se actualiza sola con cada release.': 'Updates itself with every release.',
  'Personaliza la instalación': 'Customize the installation',
  'Carpeta de instalación': 'Installation folder',
  'Cambiar': 'Change',
  'Crear acceso directo en el escritorio': 'Create a desktop shortcut',
  'Abrir DevPanel al terminar': 'Open DevPanel when finished',
  'Atrás': 'Back',
  'Paso 1 de 3 · Tu cuenta': 'Step 1 of 3 · Your account',
  '¿Cuál es tu usuario de GitHub?': "What's your GitHub username?",
  'Escríbelo o pega el enlace de tu perfil. Te buscamos mientras escribes.': 'Type it or paste your profile link. We look you up as you type.',
  'tu-usuario': 'your-username',
  'Soy yo, continuar': "That's me, continue",
  '{n} repos públicos · {m} seguidores': '{n} public repos · {m} followers',
  'No pude verificarlo ahora (límite de consultas de GitHub); seguiremos con este usuario.':
    "I couldn't verify it right now (GitHub rate limit); we'll continue with this user.",
  'Paso 2 de 3 · Tu código': 'Step 2 of 3 · Your code',
  'Crea tu código secreto': 'Create your secret code',
  'Son 4 dígitos. Es tu llave si el rostro falla.': "4 digits. It's your key if face recognition fails.",
  'Repite tu código': 'Repeat your code',
  'Escríbelo otra vez para asegurarnos de que lo recuerdas.': 'Type it again to make sure you remember it.',
  'No coinciden. Empecemos de nuevo.': "They don't match. Let's start over.",
  'Generar uno por mí': 'Generate one for me',
  'Este es tu código': 'This is your code',
  'Anótalo en un lugar seguro: no se puede recuperar.': "Write it down somewhere safe: it can't be recovered.",
  'Lo anoté, continuar': 'I wrote it down, continue',
  'Dígitos ingresados': 'Digits entered',
  'Borrar': 'Delete',
  'Confirmar': 'Confirm',
  'Paso 3 de 3 · Canal': 'Step 3 of 3 · Channel',
  '¿Qué versión quieres?': 'Which version do you want?',
  'Como eres el dueño del proyecto, puedes recibir los cambios antes que nadie.': "Since you own the project, you can get changes before anyone else.",
  'Estable': 'Stable',
  'Versiones probadas. Recomendado.': 'Tested versions. Recommended.',
  'Desarrollo': 'Development',
  'Cambios adelantados desde la rama developer.': 'Early changes from the developer branch.',
  'Descargando…': 'Downloading…',
  'Descargando DevPanel…': 'Downloading DevPanel…',
  'Conectando…': 'Connecting…',
  '{a} MB de {b} MB · {c}': '{a} MB of {b} MB · {c}',
  '{a} MB de {b} MB': '{a} MB of {b} MB',
  'Instalando…': 'Installing…',
  'Esto toma unos segundos. No cierres esta ventana.': 'This takes a few seconds. Do not close this window.',
  'Cancelar': 'Cancel',
  '¿Cancelar la instalación?': 'Cancel the installation?',
  'Continuar': 'Continue',
  'Sí, cancelar': 'Yes, cancel',
  'Activa el reconocimiento facial': 'Enable face recognition',
  'Se guarda solo una huella numérica cifrada en este equipo, nunca fotos.': 'Only an encrypted numeric fingerprint is stored on this device, never photos.',
  'Preparando el reconocimiento facial (puede tardar un minuto la primera vez)…': 'Preparing face recognition (the first time can take a minute)…',
  'Mira a la cámara y mueve un poco la cabeza…': 'Look at the camera and move your head a little…',
  'Mira de frente a la cámara': 'Look straight at the camera',
  'Gira un poco la cabeza a la izquierda': 'Turn your head slightly to the left',
  'Ahora un poco a la derecha': 'Now a little to the right',
  'Levanta ligeramente la barbilla': 'Lift your chin slightly',
  'Última: sonríe, ya casi está': 'Last one: smile, almost done',
  'Captura {a} de {b}': 'Capture {a} of {b}',
  '¡Listo!': 'Done!',
  'Omitir por ahora': 'Skip for now',
  'Activar': 'Enable',
  '¡DevPanel está listo!': 'DevPanel is ready!',
  'Instalado correctamente. Se actualizará solo desde ahora.': 'Installed successfully. It will update itself from now on.',
  'Abrir DevPanel': 'Open DevPanel',
  'Cerrar': 'Close',
  'Minimizar': 'Minimize',
  'Progreso': 'Progress',
  'Algo salió mal': 'Something went wrong',
  'Reintentar': 'Retry',
  'Instalación cancelada': 'Installation cancelled',
  'No se hizo ningún cambio en tu equipo.': 'No changes were made to your computer.',
  'No se pudo instalar': 'Could not install',
  'No se pudo registrar el rostro': 'Could not register your face',

  // ---- messages from the installer's main process
  'No se pudo encontrar la versión. Revisa tu conexión e inténtalo de nuevo.': 'Could not find the version. Check your connection and try again.',
  'Esa versión aún no tiene instalador publicado': "That version doesn't have a published installer yet",
  'No se pudo consultar la última versión estable (GitHub {n})': 'Could not query the latest stable version (GitHub {n})',
  'No se pudo consultar las versiones de desarrollo (GitHub {n})': 'Could not query the development versions (GitHub {n})',
  'Escribe un usuario o enlace de GitHub válido': 'Enter a valid GitHub username or link',
  'No existe el usuario "{u}" en GitHub': 'User "{u}" does not exist on GitHub',
  'GitHub respondió {n}. Intenta de nuevo en unos minutos.': 'GitHub responded {n}. Try again in a few minutes.',
  'Descarga fallida ({n})': 'Download failed ({n})',
  'La descarga está corrupta (la suma de verificación no coincide)': 'The download is corrupt (checksum mismatch)',
  'El código debe tener 4 dígitos': 'The code must be 4 digits',
  'No se encontró el módulo facial en la instalación': 'The face module was not found in the installation',
  'El cifrado del sistema no está disponible': 'System encryption is not available',
  'Falta Python. Instálalo desde python.org (marca "Add to PATH") y vuelve a intentarlo, o actívalo luego en Settings.':
    'Python is missing. Install it from python.org (check "Add to PATH") and try again, or enable it later in Settings.',
  'No se pudo instalar OpenCV con pip. Revisa tu conexión e inténtalo de nuevo.': 'Could not install OpenCV with pip. Check your connection and try again.',
  'Se canceló o falló el registro del rostro': 'Face registration was cancelled or failed',
  'La carpeta de instalación no es válida': 'The installation folder is not valid',
  'El canal de desarrollo está reservado para {u}': 'The development channel is reserved for {u}',
  'El instalador terminó con código {n}. Cierra DevPanel si está abierto e inténtalo de nuevo.': 'The installer exited with code {n}. Close DevPanel if it is open and try again.',
  'La instalación aún no terminó': "The installation hasn't finished yet",
};
