// Spanish (source language) -> English. Keys containing {name} are patterns: the captured
// parts are translated recursively, so "Última actividad hace 3 d" works from two entries.
export const EN: Record<string, string> = {
  // ---- generic
  'Saltar al contenido': 'Skip to content',
  'Principal': 'Main',
  'Cambiar tema': 'Toggle theme',
  'Guardar': 'Save',
  'Notificaciones': 'Notifications',
  'Borrar todo': 'Clear all',
  'Sin notificaciones': 'No notifications',
  'Actualización disponible: {n}': 'Update available: {n}',
  '{n} posibles secretos en {p}': '{n} possible secrets in {p}',
  'Instalar {n}': 'Install {n}',
  'Proyecto local: {n}': 'Local project: {n}',
  'programa': 'program',
  'local': 'local',
  'script': 'script',
  'Contraer menú': 'Collapse menu',
  'Expandir menú': 'Expand menu',
  'Fijados': 'Pinned',
  'Herramientas CLI': 'CLI tools',
  'Actualizar': 'Refresh',
  'Actualizaciones disponibles': 'Updates available',
  'Perfiles': 'Profiles',
  '{n} actualizado': '{n} updated',
  'Ya tienes todo el perfil': 'You already have the whole profile',
  'Perfil {n}: {l}': '{n} profile: {l}',
  'Perfil {n}: {c} por instalar': '{n} profile: {c} to install',
  'Perfil {n} listo': '{n} profile ready',
  'Falta instalar a mano: {l}': 'Install by hand: {l}',
  'Hacer commit': 'Commit changes',
  'Mensaje del commit': 'Commit message',
  'Cambiar de rama': 'Switch branch',
  'Comparar idiomas': 'Compare languages',
  'Buscar secretos': 'Scan for secrets',
  'Scripts de npm': 'npm scripts',
  'Claves de idioma que faltan': 'Missing translation keys',
  'Posibles secretos': 'Possible secrets',
  'Sin secretos a la vista': 'No secrets in sight',
  'Idiomas al día': 'Languages are up to date',
  'No encontré archivos de idiomas': 'No translation files found',
  'claves': 'keys',
  'faltan': 'missing',
  'posibles secretos': 'possible secrets',
  'Idiomas: faltan {n} claves': 'Languages: {n} keys are missing',
  '{n} posibles secretos': '{n} possible secrets',
  'Commit hecho': 'Committed',
  'Posibles secretos en: {f}. No se hizo el commit.': 'Possible secrets in: {f}. Nothing was committed.',
  'Posibles secretos en los cambios: no se hizo el commit': 'Possible secrets in the changes: nothing was committed',
  'No hay cambios para guardar': 'There are no changes to save',
  'El mensaje del commit no es válido (1 a 200 caracteres, una línea)': 'The commit message is not valid (1 to 200 characters, one line)',
  'Esa rama no existe': 'That branch does not exist',
  'Esa receta no aplica a este proyecto': 'That recipe does not apply to this project',
  'Sin pull requests abiertos.': 'No open pull requests.',
  'Sin issues abiertos.': 'No open issues.',
  'Sin ejecuciones.': 'No runs.',
  'Cancelado': 'Cancelled',
  'Reintentar jobs fallidos': 'Re-run failed jobs',
  'Reintentando jobs fallidos…': 'Re-running failed jobs…',
  'No se pudo reintentar': 'Could not re-run',
  'Necesitas un token de GitHub con permiso de Actions: guárdalo en Settings.': 'You need a GitHub token with Actions access: save it in Settings.',
  'Ejecución no válida': 'Invalid run',
  'Tu token no tiene permiso para reintentar workflows (Actions: write).': "Your token doesn't have permission to re-run workflows (Actions: write).",
  'No se encontró esa ejecución.': 'That run was not found.',
  'Inicio': 'Home',
  'Builds fallando': 'Failing builds',
  'Pull requests': 'Pull requests',
  'Cambios locales': 'Local changes',
  'Actividad reciente': 'Recent activity',
  'Todo en orden': 'All good',
  'Sin actividad': 'No activity',
  'Aún no agregaste carpetas.': 'You have not added any folders yet.',
  'No se pudo cargar GitHub': 'Could not load GitHub',
  'Cambios sin commitear': 'Uncommitted changes',
  'Commits por subir': 'Commits to push',
  'Commits por bajar': 'Commits to pull',
  'Rostro': 'Face',
  'Sin rostro registrado': 'No face registered',
  'Código creado': 'Code created',
  'Sin código': 'No code',
  'Atajo global para mostrar u ocultar': 'Global shortcut to show or hide',
  'Crear un token en GitHub. Para ver repos privados necesita permiso de lectura (repo, o Contents: Read en un token fine-grained).': 'Create a token on GitHub. To see private repos it needs read access (repo, or Contents: Read on a fine-grained token).',
  'Correcciones': 'Fixes',
  'Mejoras internas': 'Under the hood',
  'Cerrar': 'Close',
  'Anterior': 'Previous',
  'Siguiente': 'Next',
  'Detalle del proyecto': 'Project details',
  'Abrir en GitHub': 'Open on GitHub',
  'Ver Actions': 'View Actions',
  'Build correcto': 'Build passing',
  'Build con errores': 'Build failed',
  'Build en curso': 'Build in progress',
  'Cancelar': 'Cancel',
  'Quitar': 'Remove',
  'Eliminar': 'Delete',
  'Copiar': 'Copy',
  'Continuar': 'Continue',
  'Atrás': 'Back',
  'Activar': 'Enable',
  'Descargar': 'Download',
  'Error': 'Error',
  'Resultado': 'Result',
  'Entrada': 'Input',

  // ---- time
  'justo ahora': 'just now',
  'hace {n} min': '{n} min ago',
  'hace {n} h': '{n} h ago',
  'hace {n} d': '{n} d ago',

  // ---- lock screen / wizard
  'Bienvenido': 'Welcome',
  '¡Bienvenido!': 'Welcome!',
  'Hola, {u}': 'Hi, {u}',
  'Mira a la cámara para entrar': 'Look at the camera to sign in',
  'Ingresa tu código para entrar': 'Enter your code to sign in',
  'Ingresa tu código': 'Enter your code',
  'Mirando… quédate frente a la cámara': 'Looking… stay in front of the camera',
  'No te reconocí, intenta de nuevo o usa tu código': "I didn't recognize you, try again or use your code",
  'Código incorrecto': 'Wrong code',
  'Reconocer mi rostro': 'Recognize my face',
  'o ingresa tu código': 'or enter your code',
  'Entrar': 'Sign in',
  'Código de verificación': 'Verification code',
  'Código': 'Code',
  'Vincula tu GitHub': 'Link your GitHub',
  'Escribe tu usuario o pega el enlace de tu perfil.': 'Type your username or paste your profile link.',
  'usuario  ó  https://github.com/usuario': 'username  or  https://github.com/username',
  'Usuario o enlace de GitHub': 'GitHub username or link',
  'Vincular': 'Link',
  'Crea tu código de verificación': 'Create your verification code',
  'Son 4 dígitos. Lo usarás cuando el rostro no funcione. No se puede recuperar, así que guárdalo.':
    "4 digits. You'll use it when your face doesn't work. It can't be recovered, so keep it safe.",
  'Tu código': 'Your code',
  'Repite el código': 'Repeat the code',
  'Generar uno': 'Generate one',
  'Mostrar': 'Show',
  'Activa el reconocimiento facial': 'Enable face recognition',
  'Guardamos solo una huella numérica de tu rostro, cifrada en este equipo. Nunca fotos.':
    'We only store a numeric fingerprint of your face, encrypted on this device. Never photos.',
  'Omitir por ahora': 'Skip for now',
  'Todo listo': 'All set',
  'Entrar al panel': 'Open the panel',
  'Este es tu código: anótalo en un lugar seguro, no se puede recuperar.': 'This is your code: write it down somewhere safe, it cannot be recovered.',
  'El código debe tener 4 dígitos': 'The code must be 4 digits',
  'Los códigos no coinciden': "The codes don't match",
  'No se pudo guardar el código': 'Could not save the code',
  '¡Rostro registrado!': 'Face registered!',
  'Rostro registrado': 'Face registered',
  'No se pudo registrar el rostro': 'Could not register your face',
  '@{l} vinculado.': '@{l} linked.',
  '@{l} vinculado · código creado · rostro activado.': '@{l} linked · code created · face enabled.',
  '@{l} vinculado · código creado · rostro omitido (puedes activarlo en Settings).':
    '@{l} linked · code created · face skipped (you can enable it in Settings).',

  // ---- PIN pad
  'Crea tu código secreto': 'Create your secret code',
  'Son 4 dígitos. Es tu llave si el rostro falla.': "4 digits. It's your key if face recognition fails.",
  'Repite tu código': 'Repeat your code',
  'Escríbelo otra vez para asegurarnos de que lo recuerdas.': 'Type it again to make sure you remember it.',
  'No coinciden. Empecemos de nuevo.': "They don't match. Let's start over.",
  'Generar uno por mí': 'Generate one for me',
  'Este es tu código': 'This is your code',
  'Anótalo en un lugar seguro: no se puede recuperar.': "Write it down somewhere safe: it can't be recovered.",
  'Lo anoté, continuar': 'I wrote it down, continue',
  'Dígitos ingresados': 'Digits entered',
  'Borrar': 'Delete',
  'Confirmar': 'Confirm',
  'Cambiar código': 'Change code',
  'Código actualizado': 'Code updated',
  'Define tu código': 'Set your code',
  'Primero define tu código de verificación': 'Set your verification code first',

  // ---- sidebar / views
  'Versión web': 'Web version',
  'App de escritorio': 'Desktop app',
  'Tus proyectos': 'Your projects',
  'Proyectos': 'Projects',
  'Activos esta semana': 'Active this week',
  'Lenguajes': 'Languages',
  'Última actividad {when}': 'Last activity {when}',
  'Más recientes': 'Most recent',
  'Nombre A–Z': 'Name A–Z',
  'Favoritos primero': 'Favorites first',
  'Ordenar proyectos': 'Sort projects',
  'Buscar proyecto…': 'Search projects…',
  'Buscar proyecto': 'Search projects',
  'Ningún proyecto coincide con tu búsqueda.': 'No project matches your search.',
  'No hay repositorios públicos para mostrar.': 'There are no public repositories to show.',
  'Actividad en las últimas 24 h': 'Activity in the last 24 h',
  'Sin descripción': 'No description',
  'Marcar como favorito': 'Mark as favorite',
  'privado': 'private',
  'Sin Actions': 'No Actions',
  'En curso': 'In progress',
  'Abrir en VS Code': 'Open in VS Code',
  'Copiar git clone': 'Copy git clone',
  'Copiar enlace': 'Copy link',
  'Sin commits.': 'No commits.',
  'Recomendaciones ({n})': 'Recommendations ({n})',
  'Límite de la API de GitHub alcanzado (60/hora sin token). Intenta más tarde.': 'GitHub API limit reached (60/hour without a token). Try again later.',
  'Usuario o repositorio no encontrado.': 'User or repository not found.',
  'No se pudo cargar GitHub: {m}': 'Could not load GitHub: {m}',
  'Vincula tu usuario de GitHub en Settings': 'Link your GitHub user in Settings',
  'Escribe un usuario o enlace de GitHub válido': 'Enter a valid GitHub username or link',
  'No existe el usuario "{u}" en GitHub': 'User "{u}" does not exist on GitHub',

  // ---- recommendations
  'Sin actividad hace {n} días: retómalo o archívalo.': 'No activity for {n} days: pick it up again or archive it.',
  'Añade una descripción para que se entienda de un vistazo.': 'Add a description so it makes sense at a glance.',
  'Sin licencia: otros no saben si pueden usar el código.': "No license: others can't tell whether they may use the code.",
  'Agrega topics para que sea más fácil de encontrar.': 'Add topics to make it easier to find.',
  '{n} issues abiertos: conviene priorizarlos.': '{n} open issues: worth prioritizing.',

  // ---- local projects
  'Proyectos locales': 'Local projects',
  'Carpetas de tu equipo: estado de git y scripts de npm sin salir del panel.': 'Folders on your computer: git status and npm scripts without leaving the panel.',
  'Agregar carpeta': 'Add folder',
  'Detener': 'Stop',
  'Claude Code': 'Claude Code',
  'Proyecto': 'Project',
  'Nueva conversación': 'New conversation',
  'Escribe tu mensaje para Claude…': 'Type your message to Claude…',
  'Mensaje para Claude': 'Message for Claude',
  'Cambiar entre preguntar y editar': 'Switch between ask and edit',
  'Preguntar': 'Ask',
  'Editar': 'Edit',
  'Enviar (Enter)': 'Send (Enter)',
  'Enviar': 'Send',
  '¿Qué quieres hacer?': 'What do you want to do?',
  'Claude trabajará dentro de': 'Claude will work inside',
  'Agrega una carpeta en Local para empezar.': 'Add a folder in Local to get started.',
  'Agrega una carpeta en Local para usar Claude Code.': 'Add a folder in Local to use Claude Code.',
  'Explícame cómo está organizado este proyecto': 'Explain how this project is organized',
  'Busca posibles bugs en los últimos cambios': 'Look for possible bugs in the latest changes',
  'Sugiere pruebas que faltan': 'Suggest missing tests',
  'Solo lectura: Claude analiza y propone, no modifica archivos': 'Read-only: Claude analyzes and suggests, it does not change files',
  'Claude puede modificar archivos del proyecto': 'Claude can change files in the project',
  'Claude terminó con un error.': 'Claude finished with an error.',
  'Copiado': 'Copied',
  'código': 'code',
  'Limpiar': 'Clear',
  'Carpeta': 'Folder',
  'Scripts:': 'Scripts:',
  'Ejecutando: {x}': 'Running: {x}',
  'carpeta no encontrada': 'folder not found',
  'sin git': 'no git',
  'limpio': 'clean',
  '{n} cambios': '{n} changes',
  '↑ {n} por subir': '↑ {n} to push',
  '↓ {n} por bajar': '↓ {n} to pull',
  'git {a} listo': 'git {a} done',
  'git {a} falló': 'git {a} failed',
  'Aún no agregaste carpetas. Usa “Agregar carpeta” para ver su estado de git y ejecutar sus scripts.':
    'You have not added any folders yet. Use “Add folder” to see their git status and run their scripts.',
  'Proyecto no registrado': 'Project not registered',
  'Acción no permitida': 'Action not allowed',
  'Ese script no existe en package.json': "That script doesn't exist in package.json",
  'Listo': 'Done',
  'Falló': 'Failed',
  'Elige la carpeta de un proyecto': 'Choose a project folder',

  // ---- tools
  'Herramientas': 'Tools',
  'Utilidades de desarrollo sin salir del panel. Atajo: Ctrl + K.': 'Developer utilities without leaving the panel. Shortcut: Ctrl + K.',
  'Formatea, minifica y valida JSON.': 'Format, minify and validate JSON.',
  'Formatear': 'Format',
  'Minificar': 'Minify',
  'Validar': 'Validate',
  'Codifica o decodifica texto (UTF-8 y URL-safe).': 'Encode or decode text (UTF-8 and URL-safe).',
  'Texto o Base64…': 'Text or Base64…',
  'Codificar': 'Encode',
  'Decodificar': 'Decode',
  'Codifica o decodifica componentes de URL.': 'Encode or decode URL components.',
  'Calcula SHA-1, SHA-256 o SHA-512 de un texto.': 'Computes SHA-1, SHA-256 or SHA-512 of a text.',
  'Texto a hashear…': 'Text to hash…',
  'Genera UUID v4. Escribe cuántos quieres (1-50).': 'Generates UUID v4. Type how many you want (1-50).',
  'Generar': 'Generate',
  'Decodifica un token (no verifica la firma).': "Decodes a token (doesn't verify the signature).",
  'Fecha / Unix': 'Date / Unix',
  'Convierte timestamps y fechas. Escribe "now" para la hora actual.': 'Converts timestamps and dates. Type "now" for the current time.',
  '1700000000  ó  2024-01-01T00:00:00Z': '1700000000  or  2024-01-01T00:00:00Z',
  'Convertir': 'Convert',
  'Primera línea /patrón/flags; el resto es el texto a probar.': 'First line /pattern/flags; the rest is the text to test.',
  'Probar': 'Test',
  '✔ JSON válido: {k}': '✔ Valid JSON: {k}',
  'array ({n} elementos)': 'array ({n} items)',
  'objeto ({n} claves)': 'object ({n} keys)',
  'Un JWT tiene 3 partes separadas por puntos': 'A JWT has 3 parts separated by dots',
  '// la firma NO se verifica aquí': '// the signature is NOT verified here',
  '// exp: {d} (EXPIRADO)': '// exp: {d} (EXPIRED)',
  '// exp: {d} (vigente)': '// exp: {d} (valid)',
  'Formato de fecha no reconocido': 'Unrecognized date format',
  'La primera línea debe ser /patrón/flags, por ejemplo /\\d+/g': 'The first line must be /pattern/flags, for example /\\d+/g',
  'Sin coincidencias': 'No matches',
  '{n} coincidencia(s):': '{n} match(es):',
  '{a}  grupos: {b}': '{a}  groups: {b}',
  'Copiado al portapapeles': 'Copied to clipboard',
  'No se pudo copiar': 'Could not copy',

  // ---- software catalog
  'Software': 'Software',
  'Utilidades': 'Utilities',
  'Filtro': 'Filter',
  'Todo': 'All',
  'Instalados': 'Installed',
  'Faltan': 'Missing',
  'Instalado': 'Installed',
  'Instalar': 'Install',
  'Detectando…': 'Detecting…',
  'Volver a detectar': 'Detect again',
  'Reintentar': 'Retry',
  'Cancelar instalación': 'Cancel installation',
  'Abrir sitio web': 'Open website',
  'Abrir página de descarga': 'Open download page',
  'Control de versiones': 'Version control',
  'Tareas': 'Tasks',
  'Diseño': 'Design',
  'Entornos': 'Runtimes',
  'Bases de datos': 'Databases',
  'Servidores': 'Servers',
  'Contenedores': 'Containers',
  'Testing de API': 'API testing',
  'IA': 'AI',
  '{n} instalado': '{n} installed',
  'No se pudo instalar {n}. {e}': 'Could not install {n}. {e}',
  'No se pudo instalar {n}.': 'Could not install {n}.',
  'Este programa no se puede instalar desde aquí': "This program can't be installed from here",
  'Ya se está instalando': 'Already installing',
  'La instalación automática solo está disponible en Windows': 'Automatic installation is only available on Windows',
  'winget no está disponible en este equipo': 'winget is not available on this computer',
  'La instalación terminó con errores (código {c})': 'The installation finished with errors (code {c})',
  'Instalación cancelada': 'Installation cancelled',
  'Solo disponible en la app de escritorio': 'Only available in the desktop app',

  // ---- palette
  'Paleta de comandos': 'Command palette',
  'Escribe un comando o proyecto…': 'Type a command or project…',
  'Buscar comando': 'Search command',
  'Sin resultados': 'No results',
  'vista': 'view',
  'acción': 'action',
  'proyecto': 'project',
  'Ir a Projects': 'Go to Projects',
  'Ir a Herramientas': 'Go to Tools',
  'Ir a Proyectos locales': 'Go to Local projects',
  'Ir a Settings': 'Go to Settings',
  'Cambiar tema claro / oscuro': 'Toggle light / dark theme',
  'Recargar proyectos': 'Reload projects',
  'Herramienta: {x}': 'Tool: {x}',

  // ---- settings
  'Usuario cuyos repositorios públicos se muestran.': 'User whose public repositories are shown.',
  'usuario de GitHub': 'GitHub username',
  'Usuario de GitHub': 'GitHub username',
  'Vinculado a @{u}': 'Linked to @{u}',
  'Token de GitHub (opcional)': 'GitHub token (optional)',
  'Token de GitHub': 'GitHub token',
  'Sube el límite de la API de 60 a 5000 consultas por hora y muestra tus repos privados. Se guarda cifrado en este equipo.':
    'Raises the API limit from 60 to 5000 requests per hour and shows your private repos. Stored encrypted on this device.',
  'ghp_…  ó  github_pat_…': 'ghp_…  or  github_pat_…',
  'Token guardado (cuenta @{u}). Se usan tus repos privados y el límite alto de la API.': 'Token saved (account @{u}). Your private repos and the high API limit are used.',
  'Token guardado. Se usan tus repos privados y el límite alto de la API.': 'Token saved. Your private repos and the high API limit are used.',
  'En GitHub:': 'On GitHub:',
  'Crear un token': 'Create a token',
  '. Para ver repos privados necesita permiso de lectura (': '. To see private repos it needs read access (',
  'repo': 'repo',
  'Contents: Read': 'Contents: Read',
  ', o': ', or',
  'en un token fine-grained).': 'on a fine-grained token).',
  'Volver a comprobar': 'Check again',
  'Reemplazar token': 'Replace token',
  'Quitar token': 'Remove token',
  'Consultas restantes de la API por hora': 'API requests left this hour',
  'Incluye tus repos privados': 'Includes your private repos',
  'Pega tu token primero.': 'Paste your token first.',
  'Verificando token…': 'Verifying token…',
  'Token verificado y guardado ✔ (cuenta @{u})': 'Token verified and saved ✔ (account @{u})',
  'Token eliminado.': 'Token removed.',
  'Token guardado (cuenta @{u}). Límite de la API: {l} por hora, te quedan {r}. Se usan tus repos privados.': 'Token saved (account @{u}). API limit: {l} per hour, {r} left. Your private repos are used.',
  'Token guardado (cuenta @{u}). Se usan tus repos privados.': 'Token saved (account @{u}). Your private repos are used.',
  'Sin token: se usa el límite público de GitHub.': 'No token: the public GitHub limit applies.',
  'Token guardado para @{u}': 'Token saved for @{u}',
  'Token eliminado': 'Token removed',
  'No se pudo guardar': 'Could not save',
  'El token no tiene un formato válido': 'The token is not in a valid format',
  'GitHub rechazó el token (inválido o vencido)': 'GitHub rejected the token (invalid or expired)',
  'GitHub respondió {n}': 'GitHub responded {n}',
  'Ese token es de @{a}, pero tu cuenta vinculada es @{b}': 'That token belongs to @{a}, but your linked account is @{b}',
  'No se pudo contactar a GitHub': 'Could not reach GitHub',
  'El cifrado del sistema no está disponible': 'System encryption is not available',
  'Preferencias': 'Preferences',
  'Avisarme con una notificación cuando falle un build': 'Notify me when a build fails',
  'Al cerrar la ventana, seguir en la bandeja del sistema': 'Keep running in the system tray when the window is closed',
  'Abrir DevPanel al iniciar Windows (oculto en la bandeja)': 'Open DevPanel when Windows starts (hidden in the tray)',
  'Atajo global para mostrar u ocultar:': 'Global shortcut to show or hide:',
  '. Al ocultarse, el panel se vuelve a bloquear.': '. When hidden, the panel locks again.',
  'Alertas de build activadas': 'Build alerts enabled',
  'Alertas de build desactivadas': 'Build alerts disabled',
  'DevPanel se abrirá con Windows': 'DevPanel will open with Windows',
  'Ya no se abrirá con Windows': 'It will no longer open with Windows',
  'Build fallido en {r}': 'Build failed in {r}',
  'Idioma': 'Language',
  'Elige el idioma de la interfaz. “Automático” sigue el idioma de tu sistema.': 'Choose the interface language. “Automatic” follows your system language.',
  'Automático': 'Automatic',
  'Inicio de sesión facial': 'Face sign-in',
  'Registrar mi rostro': 'Register my face',
  'Rostro registrado. La app pedirá tu rostro al abrir.': 'Face registered. The app will ask for your face when it opens.',
  'Sin rostro registrado. La app abre sin bloqueo.': 'No face registered. The app opens without a lock.',
  'Al entrar con el rostro, pedir que gire la cabeza (anti-foto)': 'When signing in with your face, ask me to turn my head (anti-photo)',
  'Gira la cabeza hacia tu izquierda': 'Turn your head to your left',
  'Gira la cabeza hacia tu derecha': 'Turn your head to your right',
  'Muy bien, ahora vuelve a mirar al frente': 'Great, now look at the screen again',
  'No pude comprobar que eres una persona real. Gira la cabeza hacia el lado que se te pide.': "I couldn't confirm you are a real person. Turn your head to the side you are asked to.",
  'Mira a la cámara y mueve un poco la cabeza…': 'Look at the camera and move your head a little…',
  'Datos faciales eliminados': 'Face data deleted',
  'No hay rostro registrado': 'No face registered',
  'No hay PIN configurado': 'No code configured',
  'PIN incorrecto': 'Wrong code',
  'Respuesta inválida del módulo facial': 'Invalid response from the face module',
  'No se pudo ejecutar Python. Instálalo y corre: pip install -r python/requirements.txt':
    'Could not run Python. Install it and run: pip install -r python/requirements.txt',
  'No se pudo abrir la cámara': 'Could not open the camera',
  'No pude ver tu rostro con claridad. Mejora la luz e intenta de nuevo.': "I couldn't see your face clearly. Improve the lighting and try again.",
  'No te reconocí. Intenta de nuevo o usa el PIN.': "I didn't recognize you. Try again or use the code.",
  'No se pudieron descargar los modelos faciales: {e}': 'Could not download the face models: {e}',

  // ---- updates & channel
  'Actualizaciones': 'Updates',
  'Ver novedades': "See what's new",
  'Entendido': 'Got it',
  'Novedades de la versión {v}': "What's new in version {v}",
  'Aún no hay notas para esta versión.': 'There are no notes for this version yet.',
  'Cargando…': 'Loading…',
  'Novedades': "What's new",
  'Buscar actualizaciones': 'Check for updates',
  'La versión web siempre está en la última versión.': 'The web version is always the latest.',
  'Modo desarrollo: el actualizador solo funciona en la app instalada.': 'Development mode: the updater only works in the installed app.',
  'Buscando actualizaciones…': 'Checking for updates…',
  'Estás en la última versión.': "You're on the latest version.",
  'Error al actualizar: {m}': 'Update error: {m}',
  'Nueva versión {v} disponible.': 'New version {v} available.',
  'Nueva versión v{v}': 'New version v{v}',
  'Descargando… {p}%': 'Downloading… {p}%',
  'v{v} lista para instalar.': 'v{v} is ready to install.',
  'v{v} descargada': 'v{v} downloaded',
  'Reiniciar y actualizar': 'Restart and update',
  'Canal: Estable.': 'Channel: Stable.',
  'Canal: Desarrollo (cambios adelantados, solo para tu cuenta).': 'Channel: Development (early changes, for your account only).',
  'Canal: Desarrollo, reservado para DevCat-HGS y GalletasU. Esta cuenta recibirá solo versiones estables.':
    'Channel: Development, reserved for DevCat-HGS and GalletasU. This account will only get stable versions.',
};
